# Dev overrides on top of compose.yaml.
# Usage:
#   docker compose --env-file dev.env -f compose.yaml -f compose.dev.yaml up -d

services:
  auth-service:
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER}
    volumes:
      - ../../services/auth-service:/src/services/auth-service
      - ~/.nuget/packages:/root/.nuget/packages
      - ~/.dotnet:/root/.dotnet

  metadata-service:
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER}
    volumes:
      - ../../services/metadata-service:/src/services/metadata-service
      - ~/.nuget/packages:/root/.nuget/packages
      - ~/.dotnet:/root/.dotnet

  log-service:
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER}
    volumes:
      - ../../services/log-service:/src/services/log-service
      - ~/.nuget/packages:/root/.nuget/packages
      - ~/.dotnet:/root/.dotnet
